---
# Configure kvm

- name: enable service {{ item }}, and start if not started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ kvm_services_enable }}"
  when: kvm_enable_service
